# Generated by Django 4.2.10 on 2024-02-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_dec',
            field=models.TextField(blank=True, null=True),
        ),
    ]
