# Generated by Django 4.2.6 on 2024-03-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240302_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
